schedulerName: custom-scheduler

image:
  repository: public.ecr.aws/eks-distro/kubernetes/kube-scheduler
  tag: v1.30.11-eks-1-30-latest

replicaCount: 1

serviceAccount:
  create: true
  name: ""

leaderElection:
  leaderElect: true
  leaseDuration: "15s"
  renewDeadline: "10s"
  retryPeriod: "2s"

plugins:
  queueSort:
    enabled:
      - PrioritySort
  preFilter:
    enabled:
      - NodeResourcesFit
    disabled:
      - PodTopologySpread
  filter:
    enabled:
      - NodeResourcesFit
      - PodTopologySpread
    disabled: []
  score:
    enabled:
      - NodeResourcesFit
      - PodTopologySpread
    disabled: []

pluginConfig:
  - name: NodeResourcesFit
    args:
      ignoredResourceGroups:
        - "example.com"
      scoringStrategy:
        type: MostAllocated

# Add any extra fields to extend the deployment spec.template.spec here
specs:
  containers:
    - name: kube-scheduler
      resources:
        requests:
          cpu: 100m
          memory: 256Mi
        limits:
          cpu: 500m
          memory: 512Mi
      livenessProbe:
        httpGet:
          path: /healthz
          port: 10251
        initialDelaySeconds: 10
        periodSeconds: 10
