{{- if and .Values.rbac.create }}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "kube-scheduler.fullname" . }}
  labels:
    {{- include "kube-scheduler.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
subjects:
  - kind: ServiceAccount
    name: {{ include "kube-scheduler.serviceAccountName" . }}
    namespace: {{ include "kube-scheduler.namespace" . }}
roleRef:
  kind: ClusterRole
  {{- if .Values.rbac.useExistingClusterRole }}
  name: {{ .Values.rbac.useExistingClusterRole }}
  {{- else }}
  name: {{ include "kube-scheduler.fullname" . }}
  {{- end }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
