{{- if and .Values.config.create }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kube-scheduler.configMapName" . }}
  namespace: {{ include "kube-scheduler.namespace" . }}
  labels:
    {{- include "kube-scheduler.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  scheduler-config.yaml: {{ .Values.config.kubeSchedulerConfig | quote}}
{{- end }}
