{{- if and .Values.config.create }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "custom-scheduler.configMapName" . }}
  labels:
    {{- include "custom-scheduler.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  scheduler-config.yaml: |-
{{ .Values.kubeSchedulerConfig | indent 4 }}
