apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "custom-scheduler.fullname" . }}-config
  namespace: {{ include "custom-scheduler.namespace" . }}
  labels:
    app: {{ include "custom-scheduler.name" . }}
data:
  kube-scheduler-config.yaml: |
    apiVersion: kubescheduler.config.k8s.io/v1
    kind: KubeSchedulerConfiguration
    leaderElection:
      leaderElect: {{ .Values.leaderElection.leaderElect | default true }}
      leaseDuration: "{{ .Values.leaderElection.leaseDuration | default "15s" }}"
      renewDeadline: "{{ .Values.leaderElection.renewDeadline | default "10s" }}"
      retryPeriod: "{{ .Values.leaderElection.retryPeriod | default "2s" }}"
    profiles:
      - schedulerName: {{ .Values.schedulerName | quote }}
        plugins:
{{ toYaml .Values.plugins | indent 10 }}
        pluginConfig:
{{ toYaml .Values.pluginConfig | indent 10 }}
