# Default values for aws-service-quotas-exporter.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
nameOverride: ""
fullnameOverride: ""

namespaceOverride: ""

revisionHistoryLimit: 10
logLevel: INFO

image:
  repository: registry.k8s.io/kube-scheduler
  pullPolicy: IfNotPresent
  tag: ""

replicaCount: 1

serviceAccount:
  # Specify, whatever a service account should be created
  create: true
  # Service account name, or use from variables, serviceAccountName
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
   # runAsNonRoot: true
   # capabilities:
   #   drop:
   #     - ALL

resources: {}
#  limits:
#    cpu: 100m
#    memory: 128Mi
#  requests:
#    cpu: 100m
#    memory: 128Mi

nodeSelector: {}
tolerations: []
affinity: {}

config:
  schedulerName: custom-scheduler-mostallocated
  leaderElect: false
  pluginApiVersion: kubescheduler.config.k8s.io/v1
  pluginConfig:
  - args:
      scoringStrategy:
        resources:
        - name: cpu
          weight: 1
        - name: memory
          weight: 1
        type: MostAllocated
    name: NodeResourcesFit

  plugins:
    score:
      enabled:
      - name: NodeResourcesFit
        weight: 1

rbac:
  create: true
  extraClusterRoleRules: []
