name: Helm Chart Validation

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - master

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - name: Set up Helm
        uses: azure/setup-helm@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          version: v3.14.4

      - name: Lint Helm Chart(s)
        run: |
          for chart in charts/*; do
            if [ -f "$chart/Chart.yaml" ]; then
              echo "Linting $chart"
              helm lint "$chart"
            fi
          done

      - name: Run yamllint
        uses: ibiqlik/action-yamllint@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          file_or_dir: charts/kube-scheduler
